### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [MT2419/intro-data-capstone-musclehub#1]
Excellent job with the coding!

I noticed that the powerpoint has only the plots.
The purpose of powerpoint is to highlight your findings as a Data Analyst/Data Scientist to a wider audience (most probably senior management)

Best to create a powerpoint with the following structure:
(i) First slide states the "Objective"
(ii) 2-3 slides to highlight the analysis and findings using plots.
(iii) Final slide states the "Recommendation / Conclusion"

I am attaching the sample powerpoint for your reference.

Overall Good job!!
[Musclehub_sample1.pdf](https://github.com/MT2419/intro-data-capstone-musclehub/files/1856861/Musclehub_sample1.pdf)

**Comment by MT2419** [comment]
The sample was very helpful. Thank You!
